defaults:
  - _self_
  - dataset: celeb
  - diffusion: ddim_100
  - mcg_diff: default
  - task: super_resolution

save_folder: /mnt/data/gabriel/mcg_diff/images
seed: 10
plot: true
save_fig: false
save_data: false